name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clear build folder
      run: rm -rf build

    - name: Create build folder
      run: mkdir build

    - name: Install dependencies
      run: conan install . -if build --build missing

    - name: Build with CMake
      run: cmake . -B build

    - name: Build with Make
      run: make -C build
